// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "f7af8d12-79fb-448c-9de0-2c43b3de35ec");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1563575005);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1563575125);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1563585565);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1563575485);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1563575365);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1563574885);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1563313345);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1563575245);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 972800);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1563312368);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{}");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.spoc.impressions", "{\"1734\":[1563312376492],\"1773\":[1563574960396,1563575217189]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{39892f09-2427-4458-87e6-98e0f75f1009}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1563336000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1563587704283");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1563589527283");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1563585566865");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1563589166865");
user_pref("browser.search.cohort", "nov17-2");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190228215631");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1563574746");
user_pref("browser.slowStartup.averageTime", 3886);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20190228215631");
user_pref("browser.startup.homepage_override.mstone", "65.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1563312377827");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.Manjaro.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "887436a147e94627a4d9044050687d6e");
user_pref("extensions.blocklist.lastModified", "Wed, 17 Jul 2019 12:38:35 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1563575007);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190228215631");
user_pref("extensions.lastAppVersion", "65.0.2");
user_pref("extensions.lastPlatformVersion", "65.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"1f537c55-fa6f-481c-9acb-bf79c4eab129\",\"screenshots@mozilla.org\":\"de520819-c26a-4951-9f12-8562a2894497\",\"webcompat-reporter@mozilla.org\":\"31479a54-2334-4f65-a281-628f74243919\",\"webcompat@mozilla.org\":\"d3c2e7c6-dad0-4794-97f7-1c3b5d4b06e5\",\"baidu-code-update@mozillaonline.com\":\"0210a9d6-50ea-4d1f-896e-7bfc930d23d8\",\"fxmonitor@mozilla.org\":\"a29d286a-fc67-4063-822d-632882016948\"}");
user_pref("font.internaluseonly.changed", false);
user_pref("idle.lastDailyNotification", 1563576314);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1563312766);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190228215631");
user_pref("media.gmp-manager.lastCheck", 1563574761);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1563387284);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "c5a74f0d-f953-4e9c-ba99-455278d19644");
user_pref("security.sandbox.plugin.tempDirSuffix", "c241c5c8-8fb9-4efb-92ef-4bc9c27bdedd");
user_pref("services.blocklist.addons.checked", 1563575114);
user_pref("services.blocklist.gfx.checked", 1563575114);
user_pref("services.blocklist.onecrl.checked", 1563575114);
user_pref("services.blocklist.pinning.checked", 1563575114);
user_pref("services.blocklist.plugins.checked", 1563575114);
user_pref("services.settings.clock_skew_seconds", -229);
user_pref("services.settings.last_etag", "\"1563494925197\"");
user_pref("services.settings.last_update_seconds", 1563575114);
user_pref("services.settings.main.language-dictionaries.last_check", 1563575114);
user_pref("services.settings.main.onboarding.last_check", 1563575114);
user_pref("services.settings.main.sites-classification.last_check", 1563575114);
user_pref("services.settings.main.tippytop.last_check", 1563575114);
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1563387284);
user_pref("toolkit.startup.last_success", 1563574731);
user_pref("toolkit.telemetry.cachedClientID", "e3507d87-63c1-4698-9754-07ad9b9da487");
user_pref("toolkit.telemetry.previousBuildID", "20190228215631");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
